name: Deploy

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.1'
          modules: 'qtserialport'

      - name: Build
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH="%QT_ROOT_DIR%" -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          windeployqt Release\SerialFlow.exe
          powershell Compress-Archive -Path Release -DestinationPath SerialFlow-Windows.zip
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SerialFlow-Windows
          path: build/SerialFlow-Windows.zip

  build-arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel cmake qt6-base qt6-serialport git

      - uses: actions/checkout@v4
      
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          mv SerialFlow SerialFlow-Arch
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SerialFlow-Arch
          path: build/SerialFlow-Arch

  build-ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y cmake qt6-base-dev qt6-serialport-dev build-essential git

      - uses: actions/checkout@v4
      
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          mv SerialFlow SerialFlow-Ubuntu
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SerialFlow-Ubuntu
          path: build/SerialFlow-Ubuntu

  upload-assets:
    needs: [build-ubuntu, build-windows, build-arch]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Display structure of downloaded files
        run: ls -R
        
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          overwrite: true
          files: |
            SerialFlow-Windows/SerialFlow-Windows.zip
            SerialFlow-Arch/SerialFlow-Arch
            SerialFlow-Ubuntu/SerialFlow-Ubuntu
